<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>xtal</string>
	</array>
	<key>name</key>
	<string>Xtal</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comment</string>
			<key>match</key>
			<string>//.*</string>
			<key>name</key>
			<string>comment.line.xtal</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>comment</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.line.block.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operator</string>
			<key>match</key>
			<string>\+=|-=|\*=|/=|\+\+|--|&lt;&lt;=|&gt;&gt;=|&amp;=|\|=|\^=|&lt;&lt;|&gt;&gt;|&lt;=|&gt;=|==|!=|&lt;|&gt;|&amp;&amp;|\|\||!|\+|-|\*|/|&amp;|\||\^|%|=</string>
			<key>name</key>
			<string>keyword.operator.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>keyword</string>
			<key>match</key>
			<string>\b(fun|fiber|method|if|else|while|for|break|continue|yield|return|throw|try|catch|finally|class|public|protected|private|singleton)\b</string>
			<key>name</key>
			<string>keyword.control.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>constant language</string>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable language</string>
			<key>match</key>
			<string>\b(this)\b</string>
			<key>name</key>
			<string>variable.language.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string literal</string>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.double.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>string literal</string>
			<key>match</key>
			<string>'.*?'</string>
			<key>name</key>
			<string>string.quoted.single.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>number literal</string>
			<key>match</key>
			<string>\b(\d+(\.\d+)?|0[Bb][01]+|0[Xx][0-9ABCDEFabcdef]+)\b</string>
			<key>name</key>
			<string>constant.numeric.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>library</string>
			<key>match</key>
			<string>\b(to_s|to_i|to_f|p|length|acos|asin|atan|atan2|ceil|cos|exp|floor|log|pow|sin|sqrt|tan|abs|max|min|random|random_range)\b</string>
			<key>name</key>
			<string>support.function.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>library</string>
			<key>match</key>
			<string>\b(PI|E)\b</string>
			<key>name</key>
			<string>support.constant.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>library</string>
			<key>match</key>
			<string>\b(lib|grobal|math|filesystem|debug)\b</string>
			<key>name</key>
			<string>support.variable.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>library</string>
			<key>match</key>
			<string>\b(Any|Null|Undefined|Int|Float|Bool|String|Array|Map|Fun|Method|Fiber|Values|Lambda|Iterator|Iterable|ClassSet|Text|Thread|Mutex|Stream|MemoryStream|PointerStream|StringStream|FileStream|CompressEncoder|CompressDecoder|StdinStream|StdoutStream|StderrStream|Lib|Global|Exception|Range|IntRange|FloatRange|ChRange|Frame|Arguments)\b</string>
			<key>name</key>
			<string>support.type.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>function</string>
			<key>match</key>
			<string>\b\w+(?=\()</string>
			<key>name</key>
			<string>entity.name.function.xtal</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>variable</string>
			<key>match</key>
			<string>\b\w+(?=\s*:)</string>
			<key>name</key>
			<string>entity.name.variable.xtal</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.xtal</string>
	<key>uuid</key>
	<string>d515f1c3-cf0e-4059-a955-bbbb2e3491e2</string>
</dict>
</plist>
